# Generated by Django 6.0.4 on 2026-06-09 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalproperty',
            name='owner',
        ),
    ]
