# Generated by Django 6.0.4 on 2026-06-09 11:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_internalproperty_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalproperty',
            name='agent_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internalproperty',
            name='agent_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='internalproperty',
            name='agent_whatsapp',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='internalproperty',
            name='building_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internalproperty',
            name='full_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internalproperty',
            name='google_drive_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internalproperty',
            name='land_certificate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='internalproperty',
            name='listing_status',
            field=models.CharField(default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='internalproperty',
            name='owner_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
