# Generated by Django 6.0.4 on 2026-06-11 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_internalproperty_agent_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalproperty',
            name='owner_username',
        ),
        migrations.AddField(
            model_name='internalproperty',
            name='owner',
            field=models.ForeignKey(null=True,
    blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
