# Generated by Django 6.0.4 on 2026-06-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_remove_internalproperty_owner_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalproperty',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('sold', 'Sold Out')], default='active', max_length=20),
        ),
    ]
