# Generated by Django 6.0.4 on 2026-06-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_internalproperty_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalproperty',
            name='wilayah',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='internalproperty',
            name='location',
            field=models.CharField(choices=[('dki-jakarta', 'Jakarta'), ('jakarta-selatan', 'Jakarta Selatan'), ('jakarta-barat', 'Jakarta Barat'), ('jakarta-timur', 'Jakarta Timur'), ('jakarta-utara', 'Jakarta Utara'), ('jakarta-pusat', 'Jakarta Pusat'), ('tangerang', 'Tangerang'), ('tangerang-selatan', 'Tangerang Selatan'), ('bekasi', 'Bekasi'), ('depok', 'Depok'), ('bogor', 'Bogor'), ('bandung', 'Bandung'), ('surabaya', 'Surabaya'), ('medan', 'Medan'), ('semarang', 'Semarang'), ('yogyakarta', 'Yogyakarta'), ('bali', 'Bali')], max_length=50),
        ),
        migrations.AlterField(
            model_name='internalproperty',
            name='property_category',
            field=models.CharField(choices=[('rumah', 'Rumah'), ('apartemen', 'Apartemen'), ('tanah', 'Tanah'), ('ruko', 'Ruko'), ('pabrik', 'Pabrik'), ('perkantoran', 'Perkantoran'), ('ruang-usaha', 'Ruang Usaha'), ('gudang', 'Gudang'), ('villa', 'Villa'), ('kost', 'Kost'), ('hotel', 'Hotel'), ('tempat-usaha', 'Tempat Usaha'), ('kios', 'Kios')], max_length=50),
        ),
    ]
