# Generated by Django 6.0.4 on 2026-05-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('price', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
    ]
