# Generated by Django 6.0.4 on 2026-05-03 20:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_property_kata_kunci_property_max_luas_bangunan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='source',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
